Repository kowainik/autopack, pull requests merged in 2020-03, with the labels that each got.

#6 [#1] Implement initial version
  autopack.cabal
  src/Autopack.hs
  stack.yaml
Labels: enhancement

#7 [#5] Support GHC-8.6.5 and GHC-8.4.4
  .github/workflows/ci.yml
  .travis.yml
  autopack.cabal
Labels: enhancement

#8 [#4] Write README
  README.md
Labels: documentation

#10 [#9] Add Haddock docs to all exposed functions
  autopack.cabal
  src/Autopack.hs
Labels: documentation, enhancement

#11 Add support for .hsc files
  src/Autopack.hs
Labels: enhancement

#12 Update changelog, fix hlint
  CHANGELOG.md
  src/Autopack.hs
Labels: documentation, enhancement
